version: "3.4"

services:
    subsystem:
        build: .
        container_name: data_gathering_subsystem
        image: diegohermida/data_gathering_subsystem:1.0
        volumes:
            - type: volume
              source: ~/DataGatheringSubsystem/log
              target: /DataGatheringSubsystem/log
              nocopy: true
            - type: volume
              source: ~/DataGatheringSubsystem/state
              target: /DataGatheringSubsystem/state
              nocopy: true
        environment:
            - PYTHONUNBUFFERED=1
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - type: volume
              source: ~/DataGatheringSubsystem/data/db
              target: /data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles
