version: "3.4"

services:
    subsystem:
        build: .
        container_name: data_gathering_subsystem
        image: diegohermida/data_gathering_subsystem:1.1
        volumes:
            - ~/DataGatheringSubsystem/log:/DataGatheringSubsystem/log
            - ~/DataGatheringSubsystem/state:/DataGatheringSubsystem/state
        environment:
            - PYTHONUNBUFFERED=1
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - ~/DataGatheringSubsystem/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles
