version: "3.4"

services:
    data_gathering_subsystem:
        build:
            context: .
            dockerfile: ./data_gathering_subsystem/Dockerfile
        container_name: data_gathering_subsystem
        image: diegohermida/data_gathering_subsystem:latest
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/log:/ClimateChangeApp/log
            - ${ROOT_DIR:-~/ClimateChangeApp}/state:/ClimateChangeApp/state
        environment:
            - PYTHONUNBUFFERED=1
        networks:
          - app_network
    data_conversion_subsystem:
        build:
            context: .
            dockerfile: ./data_conversion_subsystem/Dockerfile
        container_name: data_conversion_subsystem
        image: diegohermida/data_conversion_subsystem:latest
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/log:/ClimateChangeApp/log
            - ${ROOT_DIR:-~/ClimateChangeApp}/state:/ClimateChangeApp/state
        environment:
            - PYTHONUNBUFFERED=1
        networks:
          - app_network
    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        container_name: api
        image: diegohermida/api:latest
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/log/api:/ClimateChangeApp/log/api
        ports:
            - "${BIND_IP_ADDRESS:-127.0.0.1}:${API_PORT:-5000}:5000"
        networks:
          - app_network
    telegram_bot:
        build:
            context: .
            dockerfile: ./telegram_bot/Dockerfile
        container_name: telegram_bot
        image: diegohermida/telegram_bot:latest
        environment:
            - PYTHONUNBUFFERED=1
        networks:
          - app_network
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/data/db:/data/db
        ports:
            - "${BIND_IP_ADDRESS:-127.0.0.1}:${MONGODB_PORT:-27017}:27017"
        networks:
          - app_network
        command: mongod --smallfiles
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - PGDATA=/postgresql/data
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/postgresql/data:/postgresql/data
        ports:
            - "${BIND_IP_ADDRESS:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432"
        networks:
          - app_network
    utilities:
        build:
            context: .
            dockerfile: ./utilities/Dockerfile
        container_name: utilities
        image: diegohermida/utilities:latest
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
          - mongodb
          - postgres
        networks:
          - app_network
    jenkins:
        build:
            context: .
            dockerfile: ./ci/Dockerfile
        image: diegohermida/jenkins:latest
        container_name: jenkins
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "0.0.0.0:${JENKINS_PORT:-8090}:8080"
            - "0.0.0.0:${JENKINS_AGENTS_PORT:-50000}:50000"
        networks:
          - app_network
    sonar:
        image: sonarqube:latest
        container_name: sonar
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:postgresql://${HOST_IP:-127.0.0.1}:${POSTGRES_SONAR_PORT:-5434}/sonar
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/sonar/extensions:/opt/sonarqube/extensions
            - ${ROOT_DIR:-~/ClimateChangeApp}/sonar/data:/opt/sonarqube/data
        ports:
            - "0.0.0.0:${SONAR_PORT:-9000}:9000"
        networks:
          - app_network
        depends_on:
          - sonar_db
    sonar_db:
        image: postgres:latest
        container_name: sonar_db
        environment:
            - PGDATA=/postgresql/data
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
            - POSRGRES_DB=sonar
        volumes:
            - ${ROOT_DIR:-~/ClimateChangeApp}/sonar/postgresql/data:/postgresql/data
        ports:
            - "${BIND_IP_ADDRESS:-127.0.0.1}:${POSTGRES_SONAR_PORT:-5434}:5432"
        networks:
          - app_network

networks:
    app_network:
        driver: bridge