version: "3.4"

services:
    data_gathering_subsystem:
        build:
            context: .
            dockerfile: ./data_gathering_subsystem/Dockerfile
        container_name: data_gathering_subsystem
        image: diegohermida/data_gathering_subsystem:2.0
        volumes:
            - ~/ClimateChangeApp/log:/ClimateChangeApp/log
            - ~/ClimateChangeApp/state:/ClimateChangeApp/state
        environment:
            - PYTHONUNBUFFERED=1
    data_conversion_subsystem:
        build:
            context: .
            dockerfile: ./data_conversion_subsystem/Dockerfile
        container_name: data_conversion_subsystem
        image: diegohermida/data_conversion_subsystem:1.0
        volumes:
            - ~/ClimateChangeApp/log:/ClimateChangeApp/log
            - ~/ClimateChangeApp/state:/ClimateChangeApp/state
        environment:
            - PYTHONUNBUFFERED=1
    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        container_name: data_gathering_subsystem_api
        image: diegohermida/data_gathering_subsystem_api:1.0.0
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ~/ClimateChangeApp/log/api:/ClimateChangeApp/log/api
        ports:
            - 5000:5000
    telegram_bot:
        build:
            context: .
            dockerfile: ./telegram_bot/Dockerfile
        container_name: telegram_bot
        image: diegohermida/telegram_bot:1.0
        environment:
            - PYTHONUNBUFFERED=1
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - ~/ClimateChangeApp/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - PGDATA=/postgresql/data
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        volumes:
            - ~/ClimateChangeApp/postgresql/data:/postgresql/data
        ports:
            - 5432:5432
