version: "3.4"

services:
    data_gathering_subsystem:
        build:
            context: .
            dockerfile: ./data_gathering_subsystem/Dockerfile
        container_name: data_gathering_subsystem
        image: diegohermida/data_gathering_subsystem:2.0
        volumes:
            - ~/DataSubsystems/log:/DataSubsystems/log
            - ~/DataSubsystems/state:/DataSubsystems/state/data_gathering_subsystem
        environment:
            - PYTHONUNBUFFERED=1
        links:
            - mongodb
        depends_on:
            - mongodb
    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        container_name: data_gathering_subsystem_api
        image: diegohermida/data_gathering_subsystem_api:1.0.0
        environment:
            - PYTHONUNBUFFERED=1
        links:
            - mongodb
        depends_on:
            - mongodb
        ports:
            - 5000:5000
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - ~/DataSubsystems/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles
