import os
from global_config.global_config import GLOBAL_CONFIG

# Database configuration
MONGO_HOST = os.environ.get(GLOBAL_CONFIG['MONGODB_SERVER'], 'localhost')
MONGO_PORT = GLOBAL_CONFIG['MONGODB_PORT']
MONGO_USERNAME = GLOBAL_CONFIG['MONGODB_USERNAME']
MONGO_PASSWORD = GLOBAL_CONFIG['MONGODB_PASSWORD']
MONGO_DBNAME = GLOBAL_CONFIG['MONGODB_DATABASE']
MONGO_AUTH_MECHANISM = GLOBAL_CONFIG['MONGODB_AUTH_MECHANISM']
MONGO_CONNECT_TIMEOUT_MS = GLOBAL_CONFIG['MONGODB_DB_MAX_MILLISECONDS_WAIT']

# Domain configuration
DOMAIN = {}

# API configuration
HATEOAS = False
IF_MATCH = False
API_ALIVE_CACHE_TIME = 10000  # 10 seconds
