from os import environ
from global_config.global_config import GLOBAL_CONFIG

# Database configuration
MONGO_HOST = environ.get(GLOBAL_CONFIG['DB_SERVER'], 'localhost')
MONGO_PORT = GLOBAL_CONFIG['DB_PORT']
MONGO_USERNAME = GLOBAL_CONFIG['DB_USERNAME']
MONGO_PASSWORD = GLOBAL_CONFIG['DB_PASSWORD']
MONGO_DBNAME = GLOBAL_CONFIG['DATABASE']
MONGO_AUTH_MECHANISM = GLOBAL_CONFIG['DB_AUTH_MECHANISM']
MONGO_CONNECT_TIMEOUT_MS = GLOBAL_CONFIG['DB_MAX_MILLISECONDS_WAIT']

# Domain configuration
DOMAIN = {}

# API configuration
HATEOAS = False
IF_MATCH = False
MODULES_CACHE_TIME = 30000  # 30 seconds
API_ALIVE_CACHE_TIME = 10000  # 10 seconds
